local root = script.Parent:WaitForChild("ClientSystems")

local ClientContext = require(root:WaitForChild("ClientContext"))
local NotificationUI = require(root:WaitForChild("NotificationUI"))
local AdminPanelUI = require(root:WaitForChild("AdminPanelUI"))
local BoardVisualSystem = require(root:WaitForChild("BoardVisualSystem"))
local UpgradeBoardUI = require(root:WaitForChild("UpgradeBoardUI"))
local XPProgressUI = require(root:WaitForChild("XPProgressUI"))
local PassiveInventoryUI = require(root:WaitForChild("PassiveInventoryUI"))
local RuneBoardUI = require(root:WaitForChild("RuneBoardUI"))
local LeaderboardUI = require(root:WaitForChild("LeaderboardUI"))
local RuntimeLoopSystem = require(root:WaitForChild("RuntimeLoopSystem"))

local context = ClientContext.Create()

NotificationUI.Init(context)
AdminPanelUI.Init(context)
BoardVisualSystem.Init(context)
UpgradeBoardUI.Init(context)
XPProgressUI.Init(context)
PassiveInventoryUI.Init(context)
RuneBoardUI.Init(context)
LeaderboardUI.Init(context)
RuntimeLoopSystem.Start(context)
